server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name 20.2.136.131;
    server_tokens off;
    location ^~ /.well-known/acme-challenge/ { root /var/www/acme; }
    location / { return 503; }
}
