import {DatabaseSync,backup} from 'node:sqlite';
import {loadEnvFile} from 'node:process';
import {resolve} from 'node:path';
import {mkdirSync,writeFileSync,copyFileSync,existsSync} from 'node:fs';
const stage=resolve('.deployment');
mkdirSync(stage,{recursive:true});
const source=new DatabaseSync(resolve('database/catalog.sqlite'),{readOnly:true});
await backup(source,resolve(stage,'catalog.sqlite'));
const counts=Object.fromEntries(['courses','teaching_groups','offerings','accounts','reviews'].map(t=>[t,source.prepare(`SELECT count(*) n FROM ${t}`).get().n]));
source.close();
const check=new DatabaseSync(resolve(stage,'catalog.sqlite'),{readOnly:true});
if(check.prepare('PRAGMA integrity_check').get().integrity_check!=='ok')throw Error('Invalid backup');
check.close();
loadEnvFile('.env');
const config={NODE_ENV:'production',HOST:'127.0.0.1',PORT:'4180',DATABASE_PATH:'/var/lib/nnu-course/catalog.sqlite',COOKIE_SECURE:'1',TRUST_LOCAL_PROXY:'1'};
for(const k of ['SMTP_HOST','SMTP_PORT','SMTP_USER','SMTP_PASS','MAIL_FROM'])if(process.env[k])config[k]=process.env[k];
writeFileSync(resolve(stage,'app.env'),Object.entries(config).map(([k,v])=>`${k}=${JSON.stringify(v)}`).join('\n')+'\n',{mode:0o600});
if(existsSync('database/admin-setup-code.txt'))copyFileSync('database/admin-setup-code.txt',resolve(stage,'admin-setup-code.txt'));
writeFileSync(resolve(stage,'manifest.json'),JSON.stringify({preparedAt:new Date().toISOString(),counts},null,2));
console.log(JSON.stringify({backup:'verified',counts,mailConfigured:!!config.SMTP_PASS}));
