import './admin.css';
import {AdminMembers} from './AdminMembers.jsx';
import {useEffect,useState} from 'react';
import {Dropdown} from './CategorySelect.jsx';
import {communityApi,communityWrite} from './community-api.js';
import {CommunityFrame,Modal,Pager,statusName} from './Account.jsx';
const actionLabels={'admin.grant':'授权或调整管理员','admin.revoke':'撤销管理员','admin.setup':'设置管理员','course.update':'修订课程资料','course.reset':'恢复原始资料','review.block':'下架评价','review.restore':'解除评价下架','report.resolved':'举报已处理','report.dismissed':'驳回举报'};
function CourseEditor({code,onClose,onSaved}){
  const [data,setData]=useState(null),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmReset,setConfirmReset]=useState(false);
  useEffect(()=>{communityApi('/api/admin/courses/'+encodeURIComponent(code)).then(d=>{setData(d);setForm({name:d.course.name,department:d.course.department,seriesMode:d.override?.series_mode||'auto',categoryIds:d.override?.categoryIds??null,groups:d.groups.map(g=>({id:g.id,teacher:g.teachers_provided?g.teachers_raw:''})),reason:''});}).catch(e=>setError(e.message));},[code]);
  async function save(e,reset=false){e?.preventDefault();if(busy)return;setBusy(true);setError('');try{await communityWrite('/api/admin/courses/'+encodeURIComponent(code),reset?{reset:true}:form);onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <Modal title={`维护课程 · ${code}`} onClose={()=>{if(!busy)onClose();}}>{error&&<p role="alert" className="inline-error">{error}</p>}{!form?<p>正在加载课程资料…</p>:<form className="community-form" onSubmit={save}><fieldset disabled={busy}><label>课程名称<input required maxLength={150} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>开课单位<input required maxLength={100} value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><label>上下册页面<Dropdown aria-label="课程归并方式" value={form.seriesMode} onChange={e=>setForm({...form,seriesMode:e.target.value})}><option value="auto">按规则归并同单位、同版本高数 / 大物上下册</option><option value="separate">此课程独立成页</option></Dropdown></label><p>保留原始课程号和评价；高数、线代等不同课程继续分开。</p><label className="check-label"><input type="checkbox" checked={form.categoryIds!==null} onChange={e=>setForm({...form,categoryIds:e.target.checked?[]:null})}/>手动维护常用分类</label>{form.categoryIds!==null?<div className="category-checks">{data.categories.map(c=><label className="check-label" key={c.id}><input type="checkbox" checked={form.categoryIds.includes(c.id)} onChange={e=>setForm({...form,categoryIds:e.target.checked?[...form.categoryIds,c.id]:form.categoryIds.filter(id=>id!==c.id)})}/>{c.name}</label>)}</div>:<p>使用原始分类与现有自动规则。</p>}<h3>授课教师</h3>{form.groups.map((g,i)=><label key={g.id}>组合 {i+1}<input aria-label={`组合 ${i+1} 教师`} maxLength={300} value={g.teacher} onChange={e=>setForm({...form,groups:form.groups.map((v,n)=>n===i?{...v,teacher:e.target.value}:v)})}/><small>原始记录：{data.groups[i].originalTeacher||'未提供'}；留空表示待补录。</small></label>)}<label>修订依据<textarea required maxLength={500} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="说明核对来源或调整理由"/></label><details><summary>学校原始课程资料</summary><p>{data.original.name} · {data.original.department}</p></details><div className="review-form-actions"><button type="button" onClick={()=>setConfirmReset(true)}>恢复学校原始资料</button><button className="review-primary">保存修订</button></div>{confirmReset&&<div className="withdraw-confirm"><span>恢复课程、分类与教师原始资料？评价内容不受影响。</span><button type="button" onClick={e=>save(e,true)}>确认恢复</button><button type="button" onClick={()=>setConfirmReset(false)}>取消</button></div>}</fieldset></form>}</Modal>;
}
export function AdminPage(){
  const [session,setSession]=useState(null),[ready,setReady]=useState(false),[tab,setTab]=useState('reports'),[feed,setFeed]=useState(null),[page,setPage]=useState(1),[status,setStatus]=useState('open'),[q,setQ]=useState(''),[query,setQuery]=useState(''),[version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[action,setAction]=useState(null),[course,setCourse]=useState('');
  async function loadSession(){try{const s=await communityApi('/api/session');setSession(s);if(s.account?.role==='admin'&&!s.account.isOwner&&!s.account.permissions?.content){setTab('courses');setStatus('all');}}catch(e){setError(e.message);}finally{setReady(true);}}
  useEffect(()=>{document.title='管理员后台 · 南师选课簿';loadSession();},[]);
  useEffect(()=>{if(session?.account?.role!=='admin')return;if(tab==='members'){setFeed({items:[],total:0,totalPages:0});return;}const c=new AbortController();setFeed(null);setError('');communityApi(`/api/admin/${tab}?${new URLSearchParams({page,status,q:query})}`,{signal:c.signal}).then(f=>{if(page>1&&page>Math.max(1,f.totalPages))setPage(Math.max(1,f.totalPages));else setFeed(f);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[session,tab,page,status,query,version]);
  async function setup(e){e.preventDefault();setBusy(true);setError('');try{await communityWrite('/api/admin/setup',Object.fromEntries(new FormData(e.currentTarget)));await loadSession();}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function execute(e){e.preventDefault();setBusy(true);setError('');const reason=new FormData(e.currentTarget).get('reason');try{await communityWrite('/api/admin/'+action.path,{...action.data,reason,resolution:reason});setAction(null);setVersion(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
  function changeTab(t){setFeed(null);setTab(t);setPage(1);setStatus(t==='reports'?'open':'all');setQ('');setQuery('');}
  function moderate(r,restore=false){setAction({title:restore?'恢复评价':'下架评价',path:'reviews/'+r.id,data:{action:restore?'restore':'block'}});}
  return <CommunityFrame title="管理员后台" className="admin-page">{error&&<p role="alert" className="inline-error">{error} <button onClick={()=>{loadSession();setVersion(v=>v+1);}}>重试</button></p>}{!ready?<p>正在连接…</p>:!session?.account?<p>请先<a href="/login?next=%2Fadmin">登录</a>或<a href="/register?next=%2Fadmin">注册账号</a>。</p>:session.account.role!=='admin'?session.adminSetupNeeded?<form className="community-form account-form" onSubmit={setup}><h2>设置首位管理员</h2><p>只有持有服务器本地初始化码的人可以设置。初始化码位于数据库目录的 admin-setup-code.txt，仅可使用一次。</p><label>管理初始化码<input required name="code" type="password" autoComplete="off" maxLength={100}/></label><p>将把当前账号 {session.account.username} 设为管理员。</p><button disabled={busy} className="review-primary">{busy?'设置中…':'设置管理员'}</button></form>:<p>此账号没有管理员权限。</p>:<><nav className="community-tabs">{[['reports','举报处理'],['reviews','评价管理'],['courses','课程维护'],['audit','操作记录'],['members','管理员管理']].filter(([t])=>session.account.isOwner||(['reports','reviews'].includes(t)&&session.account.permissions?.content)||(t==='courses'&&session.account.permissions?.courses)).map(([t,n])=><button className={tab===t?'active':''} key={t} onClick={()=>changeTab(t)}>{n}</button>)}</nav>{tab!=='members'&&<div className="community-toolbar">{['reports','reviews'].includes(tab)&&<label>状态<Dropdown aria-label="后台状态" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}>{(tab==='reports'?[['open','待处理'],['resolved','已处理'],['dismissed','已驳回']]:[['all','全部'],...Object.entries(statusName)]).map(([v,n])=><option key={v} value={v}>{n}</option>)}</Dropdown></label>}{['reviews','courses'].includes(tab)&&<form className="community-search" onSubmit={e=>{e.preventDefault();setQuery(q);setPage(1);}}><input aria-label="后台搜索" maxLength={100} value={q} onChange={e=>setQ(e.target.value)} placeholder={tab==='courses'?'课程号 / 课程名 / 开课单位':'课程号 / 课程名 / 评价内容'}/><button className="secondary-button">搜索</button></form>}<span>{feed?`${feed.total} 条记录`:'加载中…'}</span></div>}
    {tab==='members'?<AdminMembers/>:!feed&&!error?<p role="status">正在加载…</p>:feed?.items.length===0?<p className="community-empty">暂无记录</p>:tab==='courses'?<div className="admin-course-list">{feed?.items.map(c=><button className="admin-course-row" key={c.code} onClick={()=>setCourse(c.code)}><span><strong>{c.name}</strong><small>{c.code} · {c.department}</small></span><span>维护 →</span></button>)}</div>:tab==='audit'?feed?.items.map(a=><details className="admin-audit" key={a.id}><summary>{new Date(a.createdAt).toLocaleString('zh-CN')} · {a.actor} · {actionLabels[a.action]||a.action} · {a.target}</summary><pre>{JSON.stringify(JSON.parse(a.detail),null,2)}</pre></details>):feed?.items.map(r=><article className="student-review" key={r.id}><div className="community-row-heading"><h3>{r.courseName||'评价已删除'}</h3><span>{statusName[r.reviewStatus||r.status]||r.status}</span></div><p className="student-review-scope">{r.teacher} · {new Date(r.createdAt).toLocaleString('zh-CN')}</p><p className="student-review-content">{r.content||'原评价已被作者删除'}</p>{tab==='reports'?<><p className="report-reason">举报原因：{r.reason}</p>{r.resolution&&<p>处理说明：{r.resolution}</p>}{r.status==='open'&&<div className="admin-actions">{r.reviewId&&r.reviewStatus==='published'&&<button onClick={()=>moderate({id:r.reviewId})}>下架该评价</button>}<button onClick={()=>setAction({title:'标记举报已处理',path:'reports/'+r.id,data:{status:'resolved'}})}>标记已处理</button><button onClick={()=>setAction({title:'驳回举报',path:'reports/'+r.id,data:{status:'dismissed'}})}>驳回举报</button></div>}</>:<>{r.blocked===1&&<p className="report-reason">下架说明：{r.reason}</p>}<div className="admin-actions">{r.blocked===1?<button onClick={()=>moderate(r,true)}>解除下架</button>:<button onClick={()=>moderate(r)}>下架评价</button>}</div></>}</article>)}<Pager feed={feed} onPage={setPage}/>
    {course&&<CourseEditor code={course} onClose={()=>setCourse('')} onSaved={()=>{setCourse('');setVersion(v=>v+1);}}/>}{action&&<Modal title={action.title} onClose={()=>{if(!busy)setAction(null);}}><form className="community-form" onSubmit={execute}><p>{action.data.action==='restore'?'解除后恢复公开；作者主动撤回的评价会继续保持撤回。':'操作会记录在后台日志中。'}</p><label>处理说明<textarea name="reason" required maxLength={500}/></label>{error&&<p role="alert" className="inline-error">{error}</p>}<button disabled={busy} className="review-primary">{busy?'处理中…':'确认处理'}</button></form></Modal>}
    </>}
  </CommunityFrame>;
}
